/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        tbl1 = new javax.swing.JButton();
        tbl4 = new javax.swing.JButton();
        tbl7 = new javax.swing.JButton();
        tbl2 = new javax.swing.JButton();
        tbl5 = new javax.swing.JButton();
        tbl8 = new javax.swing.JButton();
        tbl3 = new javax.swing.JButton();
        tbl6 = new javax.swing.JButton();
        tbl9 = new javax.swing.JButton();
        tblA = new javax.swing.JButton();
        tblB = new javax.swing.JButton();
        tblE = new javax.swing.JButton();
        tblC = new javax.swing.JButton();
        tblD = new javax.swing.JButton();
        tblF = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        tbl0 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);

        tbl1.setText("1");
        tbl1.setEnabled(false);
        tbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl1ActionPerformed(evt);
            }
        });

        tbl4.setText("4");
        tbl4.setEnabled(false);
        tbl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl4ActionPerformed(evt);
            }
        });

        tbl7.setText("7");
        tbl7.setEnabled(false);
        tbl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl7ActionPerformed(evt);
            }
        });

        tbl2.setText("2");
        tbl2.setEnabled(false);
        tbl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl2ActionPerformed(evt);
            }
        });

        tbl5.setText("5");
        tbl5.setEnabled(false);
        tbl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl5ActionPerformed(evt);
            }
        });

        tbl8.setText("8");
        tbl8.setEnabled(false);
        tbl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl8ActionPerformed(evt);
            }
        });

        tbl3.setText("3");
        tbl3.setEnabled(false);
        tbl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl3ActionPerformed(evt);
            }
        });

        tbl6.setText("6");
        tbl6.setEnabled(false);
        tbl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl6ActionPerformed(evt);
            }
        });

        tbl9.setText("9");
        tbl9.setEnabled(false);
        tbl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl9ActionPerformed(evt);
            }
        });

        tblA.setText("A");
        tblA.setEnabled(false);
        tblA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblAActionPerformed(evt);
            }
        });

        tblB.setText("B");
        tblB.setEnabled(false);
        tblB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBActionPerformed(evt);
            }
        });

        tblE.setText("E");
        tblE.setEnabled(false);
        tblE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblEActionPerformed(evt);
            }
        });

        tblC.setText("C");
        tblC.setEnabled(false);
        tblC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCActionPerformed(evt);
            }
        });

        tblD.setText("D");
        tblD.setEnabled(false);
        tblD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDActionPerformed(evt);
            }
        });

        tblF.setText("F");
        tblF.setEnabled(false);
        tblF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblFActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Biner");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Desimal");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Oktadesimal");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Heksadesimal");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl0.setText("0");
        tbl0.setEnabled(false);
        tbl0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl0ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel1.setText("KONVERTER BILANGAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tbl0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tbl4)
                                                .addComponent(tbl1))
                                            .addComponent(tbl7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(tbl3, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tblE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tblF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tblC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tblA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tblB)
                                            .addComponent(tblD)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbl1)
                            .addComponent(tbl2)
                            .addComponent(tbl3)
                            .addComponent(tblA)
                            .addComponent(tblB)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbl4)
                            .addComponent(tbl5)
                            .addComponent(tbl6)
                            .addComponent(tblC)
                            .addComponent(tblD)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbl7)
                            .addComponent(tbl8)
                            .addComponent(tbl9)
                            .addComponent(tblE)
                            .addComponent(tblF)
                            .addComponent(jRadioButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbl0)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblEActionPerformed
        jTextField1.setText(jTextField1.getText()+"E");
    }//GEN-LAST:event_tblEActionPerformed

    private void tbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl1ActionPerformed
        jTextField1.setText(jTextField1.getText()+"1");        
    }//GEN-LAST:event_tbl1ActionPerformed

    private void tbl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl2ActionPerformed
        jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_tbl2ActionPerformed

    private void tbl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl3ActionPerformed
         jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_tbl3ActionPerformed

    private void tbl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl4ActionPerformed
        jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_tbl4ActionPerformed

    private void tbl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl5ActionPerformed

       jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_tbl5ActionPerformed

    private void tbl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl6ActionPerformed
        jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_tbl6ActionPerformed

    private void tbl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl7ActionPerformed
       jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_tbl7ActionPerformed

    private void tbl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl8ActionPerformed
       jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_tbl8ActionPerformed

    private void tbl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl9ActionPerformed
        jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_tbl9ActionPerformed

    private void tblAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblAActionPerformed

        jTextField1.setText(jTextField1.getText()+"A");
    }//GEN-LAST:event_tblAActionPerformed

    private void tblBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBActionPerformed
        jTextField1.setText(jTextField1.getText()+"B");
    }//GEN-LAST:event_tblBActionPerformed

    private void tblCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCActionPerformed
        jTextField1.setText(jTextField1.getText()+"C");
    }//GEN-LAST:event_tblCActionPerformed

    private void tblDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDActionPerformed

      jTextField1.setText(jTextField1.getText()+"D");
    }//GEN-LAST:event_tblDActionPerformed

    private void tblFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblFActionPerformed

       jTextField1.setText(jTextField1.getText()+"F");
    }//GEN-LAST:event_tblFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl0ActionPerformed
        jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_tbl0ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        tbl0.setEnabled(true);
        tbl1.setEnabled(true);
        tbl2.setEnabled(false);
        tbl3.setEnabled(false);
        tbl4.setEnabled(false);
        tbl5.setEnabled(false);
        tbl6.setEnabled(false);
        tbl7.setEnabled(false);
        tbl8.setEnabled(false);
        tbl9.setEnabled(false);
        tblA.setEnabled(false);
        tblB.setEnabled(false);
        tblC.setEnabled(false);
        tblD.setEnabled(false);
        tblE.setEnabled(false);
        tblF.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        tbl0.setEnabled(true);
        tbl1.setEnabled(true);
        tbl2.setEnabled(true);
        tbl3.setEnabled(true);
        tbl4.setEnabled(true);
        tbl5.setEnabled(true);
        tbl6.setEnabled(true);
        tbl7.setEnabled(true);
        tbl8.setEnabled(true);
        tbl9.setEnabled(true);
        tblA.setEnabled(false);
        tblB.setEnabled(false);
        tblC.setEnabled(false);
        tblD.setEnabled(false);
        tblE.setEnabled(false);
        tblF.setEnabled(false);
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        tbl0.setEnabled(true);
        tbl1.setEnabled(true);
        tbl2.setEnabled(true);
        tbl3.setEnabled(true);
        tbl4.setEnabled(true);
        tbl5.setEnabled(true);
        tbl6.setEnabled(true);
        tbl7.setEnabled(true);
        tbl8.setEnabled(false);
        tbl9.setEnabled(false);
        tblA.setEnabled(false);
        tblB.setEnabled(false);
        tblC.setEnabled(false);
        tblD.setEnabled(false);
        tblE.setEnabled(false);
        tblF.setEnabled(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        tbl0.setEnabled(true);
        tbl1.setEnabled(true);
        tbl2.setEnabled(true);
        tbl3.setEnabled(true);
        tbl4.setEnabled(true);
        tbl5.setEnabled(true);
        tbl6.setEnabled(true);
        tbl7.setEnabled(true);
        tbl8.setEnabled(true);
        tbl9.setEnabled(true);
        tblA.setEnabled(true);
        tblB.setEnabled(true);
        tblC.setEnabled(true);
        tblD.setEnabled(true);
        tblE.setEnabled(true);
        tblF.setEnabled(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton tbl0;
    private javax.swing.JButton tbl1;
    private javax.swing.JButton tbl2;
    private javax.swing.JButton tbl3;
    private javax.swing.JButton tbl4;
    private javax.swing.JButton tbl5;
    private javax.swing.JButton tbl6;
    private javax.swing.JButton tbl7;
    private javax.swing.JButton tbl8;
    private javax.swing.JButton tbl9;
    private javax.swing.JButton tblA;
    private javax.swing.JButton tblB;
    private javax.swing.JButton tblC;
    private javax.swing.JButton tblD;
    private javax.swing.JButton tblE;
    private javax.swing.JButton tblF;
    // End of variables declaration//GEN-END:variables
}
